ITShop/Models/Sach.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore.Models
{
    public class Sach
    {
        internal object EnrollmentDate;
        public int ID { get; set; }


        [Required(ErrorMessage = "Thể loại không được bỏ trống!")]
		[Display(Name = "Thể Loại")]
		public int TheLoaiID { get; set; }


        [Required(ErrorMessage = "Tên nhà xuất bản không được bỏ trống!")]
		[Display(Name = "Nhà Xuất Bản")]
		public int NhaSanXuatID { get; set; }

		[Required(ErrorMessage = "Tên tác giả không được bỏ trống!")]
		[Display(Name = "Tác Giả")]
		public int TacGiaID { get; set; }


		[StringLength(250)]
        [Required(ErrorMessage = "Tên sách không được bỏ trống!")]
		[Display(Name = "Tên Sản Phẩm")]
		public string TenSach { get; set; }


        
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
		[Display(Name = "Đơn Giá")]
		public int DonGia { get; set; }


        [StringLength(255)]
        public string? AnhBia { get; set; }
		//Tạo trường thông tin mới để lưu dữ liệu ảnh
		[NotMapped]
		[Display(Name = "Hình ảnh sản phẩm")]
		public IFormFile? DuLieuHinhAnh { get; set; }


		/*[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Ngày nhập hàng không được bỏ trống!")]
        public DateTime NgayNhap { get; set; }*/



		[DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
		[Display(Name = "Số Lượng")]
		public int SoLuong {  get; set; }


        [Column(TypeName = "ntext")]
        [DataType(DataType.MultilineText)]
		[Display(Name = "Mô Tả")]
		public string? MoTa { get; set; }


        public ICollection<DonHang_ChiTiet>? DonHang_ChiTiet { get; set; }
        public TheLoai? TheLoai { get; set; }
        public NhaSanXuat? NhaSanXuat { get; set; }
		public TacGia? TacGia { get; set; }

    }

	[NotMapped]
	public class PhanTrangSanPham
	{
		public int TrangHienTai { get; set; }
		public int TongSoTrang { get; set; }
		public List<Sach> Sach { get; set; }
		public bool HasPreviousPage => TrangHienTai > 1;
		public bool HasNextPage => TrangHienTai < TongSoTrang;
	}
}

ITShop/Areas/Admin/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Models;
using Slugify;
using System.Linq.Dynamic.Core;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Logging;
using Microsoft.AspNetCore.Authorization;

namespace BookStore.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class SachController : Controller
    {
        private readonly BookStoreDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public SachController(BookStoreDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Sach
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: SanPham/Index_LoadData
        public IActionResult Index_LoadData()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? int.Parse(length) : 0;
                int skip = start != null ? int.Parse(start) : 0;
                int totalRecords = 0;
                int filterRecords = 0;
                var sach = from r in _context.Sach
                           select new
                           {
                               ID = r.ID,
                               AnhBia = r.AnhBia,
                               TenTheLoai = r.TheLoai.TenTheLoai,
                               TenNhaSanXuat = r.NhaSanXuat.TenNhaSanXuat,
                               TenTacGia = r.TacGia.TenTacGia,
                               TenSach = r.TenSach,
                               SoLuong = r.SoLuong,
                               DonGia = r.DonGia
                              };
                totalRecords = sach.Count();
                // Sắp xếp
                if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection))
                {
                    sach = sach.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                // Tìm kiếm
                if (!string.IsNullOrEmpty(searchValue) && !string.IsNullOrWhiteSpace(searchValue))
                {
                    sach = sach.Where(r => r.TenTheLoai.Contains(searchValue) ||
                    r.TenNhaSanXuat.Contains(searchValue) ||
					r.TenTacGia.Contains(searchValue) ||
					r.TenSach.Contains(searchValue) ||
                    r.SoLuong.ToString().Contains(searchValue) ||
                    r.DonGia.ToString().Contains(searchValue));
                }
                filterRecords = sach.Count();
                var data = sach.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                {
                    draw = draw,
                    recordsFiltered = filterRecords,
                    recordsTotal = totalRecords,
                    data = data
                };
                return Json(jsonData, new System.Text.Json.JsonSerializerOptions());
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    

// GET: Sach/Details/5
public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sach == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach
                .Include(s => s.NhaSanXuat)
                .Include(s => s.TheLoai)
			    .Include(s => s.TacGia)
				.FirstOrDefaultAsync(m => m.ID == id);
            if (sach == null)
            {
                return NotFound();
            }

            return View(sach);
        }

        // GET: Sach/Create
        public IActionResult Create()
        {
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat");
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai");
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia");
			return View();
        }

        // POST: Sach/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TheLoaiID,NhaSanXuatID,TacGiaID,TenSach,DonGia,DuLieuHinhAnh,SoLuong,MoTa")] Sach sach)
        {
            if (ModelState.IsValid)
            {
				string path = "";
				// Nếu hình ảnh không bỏ trống thì upload
				if (sach.DuLieuHinhAnh != null)
				{
					string wwwRootPath = _hostEnvironment.WebRootPath;
					string folder = "/uploads/";
					string fileExtension = Path.GetExtension(sach.DuLieuHinhAnh.FileName).ToLower();
					string fileName = sach.TenSach;

					SlugHelper slug = new SlugHelper();
					string fileNameSluged = slug.GenerateSlug(fileName);

					path =   fileNameSluged + fileExtension;
					string physicalPath = Path.Combine(wwwRootPath + folder, fileNameSluged + fileExtension);
					using (var fileStream = new FileStream(physicalPath, FileMode.Create))
					{
						await sach.DuLieuHinhAnh.CopyToAsync(fileStream);
					}
				} 
                // Cập nhật đường dẫn vào CSDL
                sach.AnhBia = path ?? null;

				_context.Add(sach);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia", sach.TacGiaID);
			return View(sach);
        }

        // GET: Sach/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sach == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach.FindAsync(id);
            if (sach == null)
            {
                return NotFound();
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia", sach.TacGiaID);
			return View(sach);
        }

        // POST: Sach/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TheLoaiID,NhaSanXuatID,TacGiaID,TenSach,DonGia,DuLieuHinhAnh,SoLuong,MoTa")] Sach sach)
        {
            if (id != sach.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string path = "";

                    // Nếu hình ảnh không bỏ trống thì upload ảnh mới

                    if (sach.DuLieuHinhAnh != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        string folder = "/uploads/";
                        string fileExtension = Path.GetExtension(sach.DuLieuHinhAnh.FileName).ToLower();

                        string fileName = sach.TenSach;
                        SlugHelper slug = new SlugHelper();
                        string fileNameSluged = slug.GenerateSlug(fileName);
                        path = fileNameSluged + fileExtension;

                        string physicalPath = Path.Combine(wwwRootPath + folder, fileNameSluged + fileExtension);

                        using (var fileStream = new FileStream(physicalPath, FileMode.Create))
                        {
                            await sach.DuLieuHinhAnh.CopyToAsync(fileStream);
                        }
                    }
                    _context.Update(sach);

                    if (string.IsNullOrEmpty(path))

                        _context.Entry(sach).Property(x => x.AnhBia).IsModified = false;
                    else
                        sach.AnhBia = path;
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SachExists(sach.ID))

                    {

                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TacGia", sach.TacGiaID);
			return View(sach);
        }

        // GET: Sach/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

ITShop/Controllers/SachController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Slugify;

namespace BookStore.Controllers
{
	public class SachController : Controller
	{
		private readonly BookStoreDBContext _context;
		public SachController(BookStoreDBContext context)
		{
			_context = context;
		}
		// GET: Index
		public IActionResult Index(int? trang)
		{
			var danhSach = LayDanhSachSanPham(trang ?? 1);
			if (danhSach.Sach.Count == 0)
				return NotFound();
			else
				return View(danhSach);
		}
	private PhanTrangSanPham LayDanhSachSanPham(int trangHienTai)
		{
			int maxRows = 20;
			PhanTrangSanPham phanTrang = new PhanTrangSanPham();
			phanTrang.Sach = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.OrderBy(r => r.TheLoaiID)
			.Skip((trangHienTai - 1) * maxRows)
			.Take(maxRows).ToList();
			decimal tongSoTrang = Convert.ToDecimal(_context.Sach.Count()) / Convert.ToDecimal(maxRows);
			phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
			phanTrang.TrangHienTai = trangHienTai;
			return phanTrang;
		}

		// GET: PhanLoai
		public IActionResult PhanLoai(int? trang, string tenLoai)
		{
			var danhSachPhanLoai = LayDanhSachSanPhamTheoPhanLoai(trang ?? 1, tenLoai);
			if (danhSachPhanLoai.Sach.Count == 0)
				return NotFound();
			else
				return View(danhSachPhanLoai);
		}
		private PhanTrangSanPham LayDanhSachSanPhamTheoPhanLoai(int trangHienTai, string tenLoai)
		{
			int maxRows = 20;
			SlugHelper slug = new SlugHelper();
			var sanPhamPhanLoai = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.AsEnumerable().Where(r => slug.GenerateSlug(r.TheLoai.TenTheLoai) == tenLoai);
			PhanTrangSanPham phanTrang = new PhanTrangSanPham();
			phanTrang.Sach = sanPhamPhanLoai.OrderBy(r => r.TheLoaiID)
			.Skip((trangHienTai - 1) * maxRows)
			.Take(maxRows).ToList();
			decimal tongSoTrang = Convert.ToDecimal(sanPhamPhanLoai.Count()) / Convert.ToDecimal(maxRows);
			phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
			phanTrang.TrangHienTai = trangHienTai;
			return phanTrang;
		}

		// GET: ChiTiet
		public IActionResult ChiTiet(string tenSanPham)
		{
			SlugHelper slug = new SlugHelper();
			var sanPham = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.AsEnumerable().Where(r => slug.GenerateSlug(r.TenSach) == tenSanPham).SingleOrDefault();
			if (sanPham == null)
				return NotFound();
			else
				return View(sanPham);
		}

	}
}

ITShop/Areas/Admin/Views/Sach/Create.cshtml
@model BookStore.Models.Sach

@{
	ViewData["Title"] = "Thêm sản phẩm";
}

<div class="card">
	<h5 class="card-header">@ViewData["Title"]</h5>
	<div class="card-body">
		<form asp-action="Create"   enctype="multipart/form-data">

		<div class="mb-3">
			<label asp-for="NhaSanXuatID" class="control-label"> Nhà xuất bản </label>
			<select asp-for="NhaSanXuatID" class ="form-control" asp-items="ViewBag.NhaSanXuatID">
				<option value="">-- Chọn --</option>
			</select>
			<span asp-validation-for="NhaSanXuatID" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label asp-for="TheLoaiID" class="control-label"> Thể loại </label>
			<select asp-for="TheLoaiID" class="form-control" asp-items="ViewBag.TheLoaiID">
				<option value="">-- Chọn --</option>
			</select>
			<span asp-validation-for="TheLoaiID" class="text-danger"></span>
		</div>

			<div class="mb-3">
				<label asp-for="TacGiaID" class="control-label"> Tác giả </label>
				<select asp-for="TacGiaID" class="form-control" asp-items="ViewBag.TacGiaID">
					<option value="">-- Chọn --</option>
				</select>
				<span asp-validation-for="TacGiaID" class="text-danger"></span>
			</div>

		<div class="mb-3">
			<label asp-for="TenSach" class="control-label"> Tên sách </label>
			<input asp-for="TenSach" class="form-control" />
			<span asp-validation-for="TenSach" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label asp-for="DonGia" class="control-label"> Đơn giá </label>
			<input asp-for="DonGia" class="form-control" />
			<span asp-validation-for="DonGia" class="text-danger"></span>
		</div>

			<div class="mb-3">
				<label asp-for="DuLieuHinhAnh" class="control-label"></label>
				<input asp-for="DuLieuHinhAnh" accept="image/jpeg,image/gif,image/png" class="form-control" />
				<span asp-validation-for="DuLieuHinhAnh" class="text-danger"></span>
			</div>

		<div class="mb-3">
			<label asp-for="SoLuong" class="control-label"> Số lượng </label>
			<input asp-for="SoLuong" class="form-control" />
			<span asp-validation-for="SoLuong" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label asp-for="MoTa" class="control-label"> Mô tả </label>
				<textarea asp-for="MoTa" class="form-control"></textarea>
			<span asp-validation-for="MoTa" class="text-danger"></span>
		</div>

		<div class="mb-0">
			<button type="submit" class="btn btn-primary"><i class="fa-light fa-floppy-disk"></i> Thêm mới </button> hoặc <a asp-action="Index">Quay về danh sách</a>
		</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}

	<script src="~/lib/ckeditor5/ckeditor.js"></script>
	<script>
		ClassicEditor.create(document.querySelector('#MoTa'), {
			licenseKey: '',
		}).then(editor => {
			window.editor = editor;
		}).catch(error => {
			console.error(error);
		});
	</script>

}

ITShop/Areas/Admin/Views/Sach/Index.cshtml
@model IEnumerable<BookStore.Models.Sach>

@{
	ViewData["Title"] = "Sản phẩm";
} 

@section Styles {
	<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" />
	<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.bootstrap5.min.css" />
}

<div class="card">
<h5 class="card-header">@ViewData["Title"]</h5>
<div class="card-body">
		<div class="row mb-3">
			<div class="col-md-6">
				<p><a asp-action="Create" class="btn btn-success"><i class="fa-light fa-plus"></i> Thêm mới</a></p>
			</div>
			<div class="col-md-6 text-end">
				<div id="export-buttons"></div>
			</div>
		</div>
		<table id="datatable" class="table table-sm table-hover table-striped table-bordered mb-0">
		<thead>
			<tr>
				<th width="5%">#</th>
				<th @Html.DisplayNameFor(model => model.AnhBia)> Ảnh bìa </th>
				<th @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)> Tên thể loại </th>
				<th @Html.DisplayNameFor(model => model.NhaSanXuat.TenNhaSanXuat)> Tên nhà xuất bản </th>
				<th @Html.DisplayNameFor(model => model.TenSach)> Tên sách </th>
				<th @Html.DisplayNameFor(model => model.TacGia.TenTacGia)> Tên Tác giả </th>
				@*<th @Html.DisplayNameFor(model => model.MoTa)> Mô tả </th>*@
				<th @Html.DisplayNameFor(model => model.SoLuong)> Số lượng </th>
				<th @Html.DisplayNameFor(model => model.DonGia)> Đơn giá </th>
				<th width="5%">Sửa</th>
				<th width="5%">Xóa</th>
			</tr>
		</thead>
		</table>
</div>
</div>

@section Scripts {
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script>
		var table = $('#datatable').DataTable({
			language: {
				processing: 'Đang xử lý...',
				lengthMenu: 'Hiển thị _MENU_ dòng',
				zeroRecords: 'Không tìm thấy dòng nào phù hợp',
				info: 'Đang xem _START_ đến _END_ trong tổng số _TOTAL_ dòng',
				infoEmpty: 'Đang xem 0 đến 0 trong tổng số 0 dòng',
				emptyTable: 'Không có dữ liệu',
				infoFiltered: '(được lọc từ _MAX_ dòng)',
				infoPostFix: '',
				search: 'Tìm kiếm:',
				paginate: {
					first: '<i class="fa-duotone fa-arrow-left-to-line"></i>',
					last: '<i class="fa-duotone fa-arrow-right-to-line"></i>',
					next: '<i class="fa-duotone fa-arrow-right"></i>',
					previous: '<i class="fa-duotone fa-arrow-left"></i>'
				},
				buttons: {
					excel: '<i class="fa-duotone fa-file-excel"></i> Xuất Excel',
					copy: '<i class="fa-duotone fa-clipboard"></i> Sao chép',
					copyTitle: 'Đã sao chép',
					copySuccess: {
						_: 'Đã sao chép %d dòng vào bộ nhớ tạm.',
						1: 'Đã sao chép 1 dòng vào bộ nhớ tạm.'
					}
				}
			},
			buttons: [{
				extend: 'excelHtml5',
				title: null,
				filename: 'DanhSachSanPham',
						action: exportAllReport
			}, {
				extend: 'copyHtml5',
				title: null,
						action: exportAllReport
			}],
			processing: true,
			serverSide: true,
			filter: true, // Hiển thị ô Tìm kiếm
			orderMulti: false, // Chỉ cho sắp xếp mỗi lần 1 cột
			ajax: {
				url: '@Url.Action("Index_LoadData", "Sach", new { area = "Admin" })', // Hàm lấy dữ liệu Index_LoadData() bên trong SanPhamController
				type: 'POST',
				datatype: 'json'
			},
			columnDefs: [
				{
					targets: [1, 8, 9],
					className: 'text-center' // Cột 1 (Hình ảnh), 8 (Sửa), 9(Xóa) canh giữa
				},
				{
					targets: [6, 7],
					className: 'text-end' // Cột 6 (Số lượng), 7(Đơn giá) canh phai
				}
			],
			columns: [
				{
					// Cột 0: STT
					data: null,
					name: null,
					sortable: false, // Không cho sắp xếp
					render: function (data, type, row, meta) {
						return meta.row + meta.settings._iDisplayStart + 1;
					}
				},
				{
					// Cột 1: Hình ảnh
					data: 'AnhBia',
					name: 'AnhBia',
					sortable: false, // Không cho sắp xếp
					render: function (data, type, row, meta) {
						return '<img src="/uploads/' + row.AnhBia + '" width = "60" class="img-thumbnail" />';
					}
				},
				{
					// Cột 2: Tên loại sản phẩm
					data: 'TenTheLoai',
					name: 'TenTheLoai'
				},
				{
					// Cột 3: Tên hãng sản xuất
					data: 'TenNhaSanXuat',
					name: 'TenNhaSanXuat'
				},
				{
					// Cột 4: Tên sản phẩm
					data: 'TenSach',
					name: 'TenSach'
				},
				{
					// Cột 5: Tên tác giả
					data: 'TenTacGia',
					name: 'TenTacGia'
				},
				{
					// Cột 6: Số lượng
					data: 'SoLuong',
					name: 'SoLuong',
					render: DataTable.render.number(null, null, 0)
				},
				{
					// Cột 7: Đơn giá
					data: 'DonGia',
					name: 'DonGia',
					render: DataTable.render.number(null, null, 0)
				},
				{
					// Cột 8: Sửa
					data: null,
					name: null,
					sortable: false, // Không cho sắp xếp
					render: function (data, type, row, meta) {
						return '<a href="/Sach/Edit/' + row.ID + '"><i class="fa-light fa-pen-to-square"></i></a>';
					}
				},
				{
					// Cột 9: Xóa
					data: null,
					name: null,
					sortable: false, // Không cho sắp xếp
					render: function (data, type, row, meta) {
						return '<a href="/Sach/Delete/' + row.ID + '"><i class="fa-light fa-trash-can text-danger"></i></a>';
					}
				}
			],
			initComplete: function (settings, json) {
				table.buttons().container().appendTo('#export-buttons');
				$('#export-buttons .btn').removeClass('btn-secondary').addClass('btn-info');
				$('#datatable').wrap('<div class="table-responsive"></div>');
			}
		});

		function exportAllReport(e, dt, button, config) {
			var self = this;
			var oldStart = dt.settings()[0]._iDisplayStart;
			dt.one('preXhr', function (e, s, data) {
				// Just this once, load all data from the server...
				data.start = 0;
				data.length = 2147483647;
				dt.one('preDraw', function (e, settings) {
					// Call the original action function
					if (button[0].className.indexOf('buttons-copy') >= 0) {
						$.fn.dataTable.ext.buttons.copyHtml5.action.call(self, e, dt, button, config);
					} else if (button[0].className.indexOf('buttons-excel') >= 0) {
						$.fn.dataTable.ext.buttons.excelHtml5.available(dt, config) ?
							$.fn.dataTable.ext.buttons.excelHtml5.action.call(self, e, dt, button, config) :
							$.fn.dataTable.ext.buttons.excelFlash.action.call(self, e, dt, button, config);
					}
					dt.one('preXhr', function (e, s, data) {
						// DataTables thinks the first item displayed is index 0, but we're not drawing that.
						// Set the property to what it was before exporting.
						settings._iDisplayStart = oldStart;
						data.start = oldStart;
					});
					// Reload the grid with the original page. Otherwise, API functions like table.cell(this) don't work properly.
					setTimeout(dt.ajax.reload, 0);
					// Prevent rendering of the full data to the DOM
					return false;
				});
			});
			// Requery the server with the new one-time export settings
			dt.ajax.reload();
		}
</script>
}